# Generated by Django 6.0 on 2026-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_name', models.CharField(max_length=100, unique=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artist_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('kopis_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('relate_url', models.CharField(blank=True, max_length=500, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
